DROP TABLE COFFEE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_COFFEE;

CREATE TABLE COFFEE(
	COFFEE_NAME VARCHAR2(30) PRIMARY KEY,
	COFFEE_SHORT NUMBER(8) NOT NULL,
	COFFEE_TALL NUMBER(8) NOT NULL,
	COFFEE_GRANDE NUMBER(8) NOT NULL
);

INSERT INTO COFFEE VALUES ('오늘의 커피', 2500, 3000, 3500);
INSERT INTO COFFEE VALUES ('아메리카노', 2800, 3300, 3800);
INSERT INTO COFFEE VALUES ('카푸치노', 3300, 3800, 4300);
INSERT INTO COFFEE VALUES ('카페 라떼', 3300, 3800, 4300);
INSERT INTO COFFEE VALUES ('카라멜 라떼', 3800, 4300, 4800);
INSERT INTO COFFEE VALUES ('카페 모카', 3800, 4300, 4800);
INSERT INTO COFFEE VALUES ('카라멜 모카', 4300, 4800, 5300);
INSERT INTO COFFEE VALUES ('화이트 초콜릿 모카', 4300, 4800, 5300);
INSERT INTO COFFEE VALUES ('카라멜 마끼야또', 4300, 4800, 5300);
INSERT INTO COFFEE VALUES ('헤이즐넛 카라멜 모카', 4300, 4800, 5300);

SELECT * FROM COFFEE;
SELECT COFFEE_NAME, COFFEE_SHORT, COFFEE_TALL,COFFEE_GRANDE FROM COFFEE;

CREATE SEQUENCE SEQ_ORDER
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE SEQ_ORDER;
-- 주문테이블
DROP TABLE COFFEE_ORDER
CASCADE CONSTRAINTS;


CREATE TABLE COFFEE_ORDER(
	SEQ NUMBER(8) PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL, 
	COFFEE_NAME VARCHAR2(30) NOT NULL,
	COFFEE_SIZE VARCHAR2(30) NOT NULL,
	COFFEE_CUP NUMBER(8) NOT NULL,
	COFFEE_SYRUP VARCHAR2(20) NOT NULL,
	COFFEE_WHIPPING NUMBER(1) NOT NULL,
	COFFEE_SHOT NUMBER(1) NOT NULL,
	COFFEE_TOTAL NUMBER(8) NOT NULL,
	ORDER_DATE DATE NOT NULL
);

SELECT * FROM COFFEE_ORDER;

ALTER TABLE COFFEE_ORDER
ADD CONSTRAINT FK_COFFEE_ORDER_ID FOREIGN KEY(MEMBER_ID)
REFERENCES MEMBER(ID);

ALTER TABLE COFFEE_ORDER
ADD CONSTRAINT FK_COFFEE_ORDER_NAME FOREIGN KEY(COFFEE_NAME)
REFERENCES COFFEE(COFFEE_NAME);
